variable "aws_region" {
  description = "Região AWS onde a IAM Policy será criada."
  type        = string
  default     = "us-east-1"
  validation {
    condition     = can(regex("^[a-z]{2}-[a-z]+-\\d$", var.aws_region))
    error_message = "aws_region deve estar no formato esperado, por exemplo: us-east-1, eu-west-1, ap-southeast-2."
  }
}

variable "policy_name" {
  description = "Nome da IAM Policy."
  type        = string
  default     = "example-readonly-policy"
  validation {
    condition     = can(regex("^[\\w+=,.@-]{1,128}$", var.policy_name))
    error_message = "policy_name deve ter entre 1 e 128 caracteres e conter apenas [A-Za-z0-9+=,.@-]_"
  }
}

variable "policy_description" {
  description = "Descrição da IAM Policy."
  type        = string
  default     = "Custom IAM policy (generated by Terraform)"
  validation {
    condition     = length(var.policy_description) <= 1000
    error_message = "policy_description deve ter no máximo 1000 caracteres."
  }
}

variable "path" {
  description = "Caminho (path) da IAM Policy."
  type        = string
  default     = "/"
  validation {
    condition     = startswith(var.path, "/") && endswith(var.path, "/")
    error_message = "path deve começar e terminar com '/'. Ex: '/', '/service-role/'."
  }
}

variable "effect" {
  description = "Efeito do statement gerado (Allow ou Deny). Ignorado se policy_json for fornecido."
  type        = string
  default     = "Allow"
  validation {
    condition     = contains(["Allow", "Deny"], var.effect)
    error_message = "effect deve ser 'Allow' ou 'Deny'."
  }
}

variable "allowed_actions" {
  description = "Lista de ações permitidas/negadas no statement padrão. Ignorado se policy_json for fornecido."
  type        = list(string)
  default     = ["s3:ListAllMyBuckets", "s3:GetBucketLocation"]
  validation {
    condition     = length(var.allowed_actions) > 0
    error_message = "allowed_actions não pode ser vazio."
  }
}

variable "allowed_resources" {
  description = "Lista de ARNs de recursos para o statement padrão. Use '*' para todos. Ignorado se policy_json for fornecido."
  type        = list(string)
  default     = ["*"]
  validation {
    condition     = length(var.allowed_resources) > 0
    error_message = "allowed_resources não pode ser vazio."
  }
}

variable "statement_sid" {
  description = "SID opcional para o statement padrão. Ignorado se policy_json for fornecido."
  type        = string
  default     = "DefaultStatement"
  validation {
    condition     = can(regex("^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$", var.statement_sid))
    error_message = "statement_sid deve começar com letra/número e ter até 128 caracteres (A-Za-z0-9_-)."
  }
}

variable "policy_json" {
  description = "JSON completo da policy (substitui o statement padrão se fornecido)."
  type        = string
  default     = null
  validation {
    condition     = var.policy_json == null || (length(trim(var.policy_json)) > 0 && can(jsondecode(var.policy_json)))
    error_message = "policy_json deve ser um JSON válido e não vazio quando fornecido."
  }
}

variable "tags" {
  description = "Tags a serem aplicadas à IAM Policy."
  type        = map(string)
  default     = {}
}
